#!/usr/bin/env bash
set -euo pipefail

function safe_7zip() {
    # 7zip, when extracting, can complain about these problems:
    # ERROR: Dangerous link path was ignored : ...
    # ERROR: Dangerous link via another link was ignored : ...
    # Since these are expected, we run it with `|| true` to suppress these errors
    7z x -o"$2" "$1" || true
}

# Extract Apple's iso discs and ipsw files

INPUT_FILE="$(realpath "$1")"
OUTPUT_DIR="$(realpath "$2")"

if [[ "$INPUT_FILE" = *".iso" || "$INPUT_FILE" = *".ipsw" ]]; then
    7z x -o"$OUTPUT_DIR" "$INPUT_FILE"
else
    echo "Unknown file format" >&2
    exit 1
fi

find "$OUTPUT_DIR" -name "*.dmg.aea" | \
while IFS= read -r AEA; do
    ipsw fw aea "$AEA"
    rm "$AEA"
done

while true; do
    SHOULD_BREAK=1
    while IFS= read -r DMG; do
        if [[ -d "${DMG}_contents" ]]; then
            continue
        fi

        if [[ "$(basename "$DMG")" = "._"* ]]; then
            mkdir "${DMG}_contents"
            continue
        fi

        SHOULD_BREAK=0
        mkdir "${DMG}_contents"
        FILE_CONTENT=$(file -b "$DMG")
        if [[ "$FILE_CONTENT" = "Apple File System"* ]]; then
            mkdir "$DMG.mount"
            apfs-fuse "$DMG" "$DMG.mount"
            cp -rdT "$DMG.mount/root" "${DMG}_contents"
            umount "$DMG.mount"
            rm -rf "$DMG.mount"
        elif [[ "$FILE_CONTENT" = "zlib compressed data" || \
                "$FILE_CONTENT" = "lzfse compressed, compressed tables" || \
                "$FILE_CONTENT" = "DOS/MBR boot sector"* ]]; then
            safe_7zip "$DMG" "${DMG}_contents"
        elif [[ "$FILE_CONTENT" = "xar archive"* ]]; then
            xar -C "${DMG}_contents" -xf "$DMG"
        elif [[ "$FILE_CONTENT" = "data" ]]; then
            continue
        else
            echo "Unknown format: $FILE_CONTENT"
        fi

        find "${DMG}_contents" -exec chmod --quiet 'u=rwX,go=rX' {} \;
    done < <(find "$OUTPUT_DIR" -type f -name "*.dmg")

    if [ "$SHOULD_BREAK" -eq 1 ]; then
        break
    fi
done

find "$OUTPUT_DIR" -type f -name "*.pkg" | \
while IFS= read -r PKG; do
    if ! xar -tf "$PKG" | grep -q Payload; then
        return 0;
    fi

    mkdir "${PKG}_tmp" "${PKG}_contents"
    xar -C "${PKG}_tmp" -xf "$PKG" Payload

    # Check if the file begins with 'pbzx'
    if [ "$(head -c4 "${PKG}_tmp/Payload" | base64)" = "cGJ6eA==" ]; then
        pbzx -n "${PKG}_tmp/Payload" > "${PKG}_tmp/Payload.cpio"
    else
        zcat "${PKG}_tmp/Payload" > "${PKG}_tmp/Payload.cpio"
    fi

    safe_7zip "${PKG}_tmp/Payload.cpio" "${PKG}_contents"
    rm -rf "${PKG}_tmp"
done
