#@ load("@ytt:data", "data")
#@ load("@ytt:overlay", "overlay")
#@ load("/lib/create-component.lib.yml", "single_build_component")

#@ source_url = "https://github.com/c-ares/c-ares/releases/download/v1.33.1/c-ares-1.33.1.tar.gz"

#@yaml/text-templated-strings
---
#@ def cares_args():
license: LICENSE.md
configure: |
  mkdir -p "$BUILD_DIR"
  extract.sh --into "$BUILD_DIR" (@= source_url @)

  cd "$BUILD_DIR"
  ./configure \
    --disable-static \
    --enable-shared \
    --prefix="$ORCHESTRA_ROOT"
build_system: make
build_dependencies:
  - host-c-toolchain
dependencies:
  - host-libc
#@ end

#@overlay/match by=overlay.all, expects=1
#@overlay/match-child-defaults missing_ok=True
---
components:
  cares: #@ single_build_component(**cares_args())
