#@ load("@ytt:data", "data")
#@ load("@ytt:overlay", "overlay")
#@ load("/lib/create_component.lib.yml", "single_build_component")

#@ source_url = "https://github.com/nodejs/node/archive/refs/tags/v18.13.0.tar.gz"

#@yaml/text-templated-strings
---
#@ def nodejs_args():
license: LICENSE
configure: |
  mkdir -p "$BUILD_DIR"
  extract.sh --into "$BUILD_DIR" "(@= source_url @)"
  cd "$BUILD_DIR"
  
  patch -p1 < "${ORCHESTRA_DOTDIR}/patches/nodejs-18-fixes.patch"
  ./configure \
    --prefix="$ORCHESTRA_ROOT" \
    --ninja \
    --with-intl=system-icu \
    --shared-openssl \
    --shared-zlib
  
install: |
  cd "$BUILD_DIR"
 
  make
  if [ "$RUN_TESTS" -eq 1 ]; then
    OPENSSL_CONF=/dev/null make test-only
  fi
  make install DESTDIR="$DESTDIR"
build_dependencies:
  - host-cxx-toolchain
  - ninja
  - python
dependencies:
  - host-libcxx
  - icu
  - openssl
  - zlib
#@ end

#@overlay/match by=overlay.all, expects=1
#@overlay/match-child-defaults missing_ok=True
---
components:
  nodejs: #@ single_build_component(**nodejs_args())
