#@ load("@ytt:overlay", "overlay")

#@overlay/match by=overlay.all, expects=1
#@overlay/match-child-defaults missing_ok=True
---
components:
  revng-development:
    builds:
      default:
        dependencies:
          - test/revng
          - test/revng-c
          - toolchain/host/gdb
          - revng-vscode-web
          - revng-distributable
          - llvm-documentation
        configure: mkdir -p "$BUILD_DIR"
        install: echo "Nothing to do"
