#@ load("@ytt:overlay", "overlay")
#@ load("/lib/create_component.lib.yml", "single_build_component")

#@yaml/text-templated-strings
---
#@ def revng_distributable():
binary_archives: private
configure: |
  mkdir -p "$BUILD_DIR"
install: |
  INSTALLER="$ORCHESTRA_DOTDIR/support/revng-distributable/install.sh"
  echo "c06811f6efeb35492f4bc8619e6b579296dfac5571162e97f05ab3671f7f2bcd $INSTALLER" | \
    sha256sum --quiet -c -
  "$INSTALLER"
dependencies:
  - revng-c
build_dependencies:
  - test/revng-qa
skip_post_install: true
#@ end

#@overlay/match by=overlay.all, expects=1
#@overlay/match-child-defaults missing_ok=True
---
components:
  revng-distributable: #@ single_build_component(**revng_distributable())
