#@ load("@ytt:overlay", "overlay")
#@ load("@ytt:template", "template")
#@ load("/lib/pip.lib.yml", "pip_package")

#@ def params():
name: revng-python-dependencies
dependencies:
- python-base-packages
#! TODO: Fix problem with python package using common dependecies and causing
#! conflicts
- revng-qa-python-dependencies
- pyyaml
- cython
requirements: |-
  # Python language checkers/formatters
  black>=22.12.0,<23.0
  flake8>=5.0.4,<6.0
  flake8-breakpoint>=1.1.0,<2.0
  flake8-builtins>=2.1.0,<3.0
  flake8-comprehensions>=3.10.1,<4.0
  flake8-eradicate>=1.4.0,<2.0
  flake8-return>=1.2.0,<2.0
  flake8-simplify>=0.19.3,<1.0
  pep8-naming>=0.13.3,<1.0
  isort>=5.11.4,<6.0
  mypy==0.982

  # Python types, needed for mypy to work correctly
  types-backports
  types-PyYAML
  types-requests
  types-urllib3

  # cmake-format executable
  cmakelang

  # Applications/Script dependencies
  aiodataloader
  ariadne[asgi-file-uploads]>=0.16
  cffi
  Jinja2
  gql[aiohttp]
  grandiso
  jsonschema
  networkx
  pefile
  pycparser
  pydot
  pyelftools

  # This is our fork of the python-idb package that includes some fixes.
  https://github.com/revng/python-idb/archive/08ba07a.tar.gz

  # pydot 3.0.2 introduced an incompatibility with pydot which is supposed to be
  # resolved in a later version, but still causes problems to us (for instance,
  # monotone framework headers generation fails), so we request v2.4.7.  See
  # https://github.com/pydot/pydot/issues/277
  pyparsing==2.4.7

  pytest
  pytest-asyncio
  requests
  requests-toolbelt
  rich

  # uvicorn[standard] but without watchfiles (since it requires rust)
  uvicorn==0.18.3
  httptools>=0.5.0
  python-dotenv>=0.13
  uvloop>=0.14.0,!=0.15.0,!=0.15.1
  websockets>=10.0

  xdg
#@ end

#@overlay/match by=overlay.all, expects=1
#@overlay/match-child-defaults missing_ok=True
---
components:
  _: #@ template.replace(pip_package(**params()))
