#@ load("@ytt:overlay", "overlay")
#@ load("@ytt:data", "data")

#@yaml/text-templated-strings
---
#@ def vscode_web_component():
repository: vscode
license: LICENSE.txt
default_build: default
binary_archives: private
builds:
  #@ for flavor in ["default", "debug"]:
  (@= flavor @):
    build_dependencies:
    - revng-js-prerequisites
    - libxkbfile
    - libx11
    - nodejs-support
    configure: |
      rm -rf "$BUILD_DIR/vscode"
      mkdir -p "$BUILD_DIR/vscode"
      cd "$BUILD_DIR/vscode"

      rsync -aq \
        --exclude=.git \
        --exclude-from=<(git -C "$SOURCE_DIR" ls-files --exclude-standard -oi --directory) \
        "$SOURCE_DIR/" .

      true > "$BUILD_DIR/yarn-cat-lock"
      find . -type f -name yarn.lock ! -path '*/node_modules/*' -printf '%h\n' | sort | \
      while IFS= read -r directory; do
        pushd "$directory" &> /dev/null
        cat yarn.lock >> "$BUILD_DIR/yarn-cat-lock"
        "$ORCHESTRA_DOTDIR"/support/fetch-js-dependencies yarn
        popd &> /dev/null
      done

      cd "$BUILD_DIR"
      sha256sum yarn-cat-lock > yarn-cat-lock.sha256

    install: |
      cd "$BUILD_DIR/vscode"

      rsync -aq \
        --exclude-from=<(git -C "$SOURCE_DIR" ls-files --exclude-standard -oi --directory) \
        "$SOURCE_DIR/" .

      true > "$BUILD_DIR/yarn-cat-lock"
      find . -type f -name yarn.lock ! -path '*/node_modules/*' -printf '%h\n' | sort | \
      while IFS= read -r directory; do
        cat "$directory/yarn.lock" >> "$BUILD_DIR/yarn-cat-lock"
      done

      pushd "$BUILD_DIR" &> /dev/null
      if ! sha256sum --quiet -c yarn-cat-lock.sha256; then
        echo "One or more package locks have changed since configure, please reconfigure or clean" > /dev/stderr
        exit 1
      fi
      popd &> /dev/null

      # Install dependencies, this process is mostly offline with the following exceptions
      # (to the best of our knowledge):
      # * vscode-web, when building electron targets, will download the prebuilt electron for the
      #   target to bundle with the build js files (this will be accounted for when building
      #   targets using electron)
      npm_config_nodedir="$ORCHESTRA_ROOT" \
      VSCODE_SKIP_NODE_VERSION_CHECK=1 \
      ELECTRON_SKIP_BINARY_DOWNLOAD=1 \
      PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD=1 \
        yarn

      # Build vscode
      revng/web/build.sh \
        "${DESTDIR}${ORCHESTRA_ROOT}/share/vscode-web-vanilla.tar.xz" \
        (@= "1" if flavor == "default" else "0" @)
  #@ end
#@ end

#@overlay/match by=overlay.all, expects=1
#@overlay/match-child-defaults missing_ok=True
---
components:
  vscode-web: #@ vscode_web_component()
