#@ load("@ytt:data", "data")
#@ load("@ytt:overlay", "overlay")
#@ load("/lib/create-component.lib.yml", "single_build_component")
#@ load("/lib/cmake.lib.yml", "cmake")

#@ source_url = "https://github.com/zlib-ng/zlib-ng/archive/refs/tags/2.2.2.tar.gz"

#@yaml/text-templated-strings
---
#@ def zlib_args():
license: LICENSE.md
configure: |
  mkdir -p "$BUILD_DIR"
  extract.sh --into "$BUILD_DIR" "(@= source_url @)"
  cd "$BUILD_DIR"

  (@= cmake @) \
    -DZLIB_ENABLE_TESTS=OFF \
    -DWITH_GTEST=OFF \
    -DZLIB_COMPAT=ON
build_system: make
post_install: |
  rm "${DESTDIR}${ORCHESTRA_ROOT}/lib/libz.a"
build_dependencies:
  - cmake
  - gcc-host-toolchain
  - glibc
dependencies:
  - host-libc
#@ end

#@overlay/match by=overlay.all, expects=1
#@overlay/match-child-defaults missing_ok=True
---
components:
  zlib: #@ single_build_component(**zlib_args())
